//Try catch kullanimi
let products;

try {
    items.forEech(item => console.log(item));

}
catch (error) {

    console.log("error:", error)
    // products = [1,2,3,4,5]
    // products.forEach(item => console.log(item));
}



console.log("Hata yönetimi düzgün calisiyor mu?")

let info = "kodluyoruz"
console.log(info)   